### ISSUE TITLE
JOSS review: Documentation general comment

### ISSUE THREAD

**Issue by astrom-tom** [0xCoto/Virgo#10]
Dear @0xCoto.

Here is a global comment about the documentation. I will create other issues with specific comments.

For such a software I believe that having the complete documentation inside the readme
is probably not appropriate and restrain a bit its content.
For python development, I would advise to use Sphinx to create a documentation that can
be then 'attached' directly to Github. It gives a great flexibility on the content
and its organization. That would greatly help the readibility. A nice example can be seen
here https://fpavogt.github.io/fcmaker/. 

If you want to keep the readme format, you will have to at least add the statement of need (it is in the paper) and the community guidelines

**Comment by 0xCoto** [comment]
@astrom-tom - Thank you for raising this important issue and suggesting a solution.

The README has just been slightly shortened (subtracting specific details concerning the usage of the package), and the documentation has been composed and can be found **[here](https://virgo.readthedocs.io/en/latest/)**.

Since it is unlikely that a reviewer would have access to appropriate hardware, we have included an example observation file obtained with Virgo on the [repository](https://github.com/0xCoto/Virgo/tree/master/joss_example) for software testing and verification purposes, as described [here](https://virgo.readthedocs.io/en/latest/examples.html#offline-experiments). Please let me know if this is sufficient, or if you were envisioning something else.

Lastly, the contributor guidelines have been composed and added to the [README](https://github.com/0xCoto/Virgo/blob/master/README.md#contributing) along with the statement of need.

**Comment by ygrange** [comment]
I do not really understand point 1 in the contribution section. For the rest: good that it's there :)

**Comment by 0xCoto** [comment]
@ygrange - Thanks for pointing that out. I've taken it out (a52df12) after a second read because it doesn't really make much sense for this package indeed.

**Comment by astrom-tom** [comment]
Hey @0xCoto ,

Thanks for the  new documentation! It looks good! One detail that would be nice is to have the table of content on the left as well.
If you can do that I will close this ticket!

Thanks!

**Comment by 0xCoto** [comment]
@astrom-tom [Done!](https://virgo.readthedocs.io/en/latest/)

**Comment by astrom-tom** [comment]
Great! Did you put the community guidelines somewhere because I can not find them.

**Comment by 0xCoto** [comment]
They are in [this readme section](https://github.com/0xCoto/Virgo#contributing).

https://github.com/0xCoto/Virgo/blob/master/docs/contributing.md

**Comment by astrom-tom** [comment]
alright. Then I will close this ticket! thanks for the work!
