### ISSUE TITLE
JOSS review: Installation and Usage

### ISSUE THREAD

**Issue by astrom-tom** [0xCoto/Virgo#11]
Dear @0xCoto 

Here are some comments about the instruction:

There is something that is not clear from the installation part of the README. It is stated:
'To use Virgo, make sure Python and GNU Radio (with gr-osmosdr) are installed on your machine.'

Is 'gr-osmosdr' part of GNU Radio? When I go to the gr-osmosdr website it is said 
'Marcus D. Leech has kindly integrated the forementioned build steps into his gnuradio installation script at "This is the most user-friendly option so far.'

So it is not clear what I have to install. I could install gnu-radio without problem but I will not install other things if they are not necessary. Please make this clearer.

Usage:
Also, you mention, in 'Usage' to use 'python virgo.py [arguments]'. I believe that if I install the package via pip I do not 
have access directly to virgo.py unless I go to the installation directory and use it from here (which is not the point of installing a package)

Example Usage:
The example usage of the readme is relatively short and could be expanded and better explained. What are you trying to do, and what do you expect as a result?

**Comment by 0xCoto** [comment]
The installation instructions have been rewritten to be more explicitly clear about the role of the `gr-osmosdr` block. Since GNU Radio is used for the acquisition and early-stage (real-time) digital signal processing of the data, unless you _do_ happen to have an SDR at hand, I wouldn't consider it a necessity for testing the package.

All of the built-in functionalities (other than `virgo.observe`) can be tested by simply running `pip install astro-virgo` and do not require GNU Radio/`gr-osmosdr` or any particular hardware. To avoid future confusions, this clarification has been added to the [documentation](https://virgo.readthedocs.io/en/latest/installation.html#dependencies).

As for the usage, you are correct that it's not obvious how one would run the script with command-line arguments. We've just pushed an update for this, and the user can now run Virgo from the command line with e.g. `virgo -h` (although as described in the documentation, this method is typically preferred for quick hardware-verification tests etc. rather than extended functionality, so I'd suggest experimenting with Virgo as a module for maximum versatility). There are no particular instructions for getting the command built into one's system, as [`setup.py`](https://github.com/0xCoto/Virgo/blob/master/setup.py) is properly configured to automatically install the command upon the installation of the package (e.g. with `pip`).

The example usage has been transferred to the [documentation](https://virgo.readthedocs.io/en/latest/examples.html) with an explanation for each function called. The [reference page](https://virgo.readthedocs.io/en/latest/reference.html) furthermore includes function-specific clarifications for each parameter.

**Comment by ygrange** [comment]
Cool to read the install docs! I would advice you to add something to the installation section in the README where you discuss the installation to add a sentence like the Note in the docs, with a link to the docs for more info.

**Comment by ygrange** [comment]
Also: Is installing the github master version a good idea for users? If so it may be useful to add to the docs (seems as easy as clonign the repo and run `pip install .` ).

**Comment by 0xCoto** [comment]
> I would advice you to add something to the installation section in the README where you discuss the installation to add a sentence like the Note in the docs, with a link to the docs for more info.

Good idea, added!

> Is installing the github master version a good idea for users?

Yup, that's perfectly reasonable - nothing stopping you from installing the package this way.

Just added a mention for this possibility to the [installation section](https://virgo.readthedocs.io/en/latest/installation.html).

**Comment by astrom-tom** [comment]
That all seems very good! Thank for updating everything in the documentation. The dependencies are now much clearer and the Usage and Example are also good. Great work!
