### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by Depal1** [0xCoto/Virgo#2]
I beg you pardon. Are there any plans to upgrade the existing code from Python 2 to Python 3? @0xCoto

**Comment by 0xCoto** [comment]
It shouldn't be a lot of work to make the code compatible with Python 3. What would have to change is [lines 45-57](https://github.com/0xCoto/VIRGO/blob/master/observe.py#L45-L57), but it's not very easy for me to test the code with Python 3 due to GNU Radio version problems. But if you'd like to give it a shot, you are more than encouraged to submit a pull request!

**Comment by 0xCoto** [comment]
Resolved! Virgo is now compatible with both Python 2 and 3.
